// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using shoes_app.Data;

#nullable disable

namespace shoes_app.Migrations
{
    [DbContext(typeof(ShoesContext))]
    [Migration("20230719091924_initial_db")]
    partial class initial_db
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("shoes_app.Models.Entity.Shoes", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasColumnOrder(3);

                    b.Property<int?>("Price")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("price")
                        .HasColumnOrder(5);

                    b.Property<DateTime?>("YearProduction")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("year_production")
                        .HasColumnOrder(4);

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("brand")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("shoes");
                });
#pragma warning restore 612, 618
        }
    }
}
